name: Build macOS App

on:
  push:
    branches:
      - master  # Запуск при push в ветку main
  workflow_dispatch:  # Возможность запускать вручную

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app

      - name: Build macOS app
        run: |
          python setup.py py2app

      - name: Upload macOS app
        uses: actions/upload-artifact@v3  # Новая версия
        with:
          name: real_love_app
          path: dist/*.app  # Указываем путь к вашему приложению в dist
